#!/usr/bin/env python3
"""molcharge-validate — cross-validate charge_vs_ph engines against EXPERIMENTAL pKa data (LOCAL, offline).

Reference sets (all measured, none predicted):
  A  IUPAC Dissociation-Constants high-confidence set (Zenodo 10.5281/zenodo.11224309; licence per that record, not verified here; NOT redistributed, kept OUTSIDE
     the repo under $MOLCHARGE_DATA_DIR) → per molecule the median macro pKa of each dissociation step at 20–30 °C, no
     cosolvent, assessment Reliable/Approximate → the experimental net-charge curve by the sequential macro model
         f_k ∝ 10^(k·pH − Σ_{j≤k} pKa_j),   Z_ref(pH) = Σ_k f_k · (q_max − k),   q_max = number of pKaH steps
     (a titration curve IS the measurement of these constants; Z(pH) is the same data re-expressed).
  B  SAMPL6 pKa challenge experimental values (Sirius T3 UV-metric titration; samplchallenges/SAMPL6) → macro pKa
     lists for 24 drug-like molecules; compared with the macro pKa read off each engine's curve (half-integer crossings).
  C  reference_literature.json — literature macro pKa with citations (e.g. ATP/ADP/AMP), same treatment as A.

Metrics per molecule: max|ΔZ| on pH 0–14, |ΔZ| at pH 7.0/7.4, ΔpI, per-step pKa error (nearest crossing).
Usage:
  molcharge-validate [--engine dimorphite] [--iupac CSV] [--sampl6 DIR] [--extra JSON] [--out STEM]
  molcharge-validate --selftest
"""
from __future__ import annotations

import argparse
import csv
import json
import math
import os
import re
import statistics
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
from . import charge as cvp  # noqa: E402

DATA_DIR = os.environ.get("MOLCHARGE_DATA_DIR", "data")   # IUPAC + SAMPL6 files are NOT shipped (licences differ)
IUPAC_CSV = os.path.join(DATA_DIR, "iupac_high-confidence_v2_3.csv")
SAMPL6_DIR = DATA_DIR
EXTRA_JSON = str(HERE / "reference_literature.json")
GRID = [round(0.1 * i, 1) for i in range(141)]

# name → SMILES (identity codes are generated by smiles_validate at run time, never typed)
IUPAC_SET = {
    "glycine": "NCC(=O)O", "L-alanine": "C[C@H](N)C(=O)O", "L-histidine": "N[C@@H](Cc1c[nH]cn1)C(=O)O",
    "L-lysine": "NCCCC[C@H](N)C(=O)O", "L-glutamic acid": "N[C@@H](CCC(=O)O)C(=O)O",
    "L-aspartic acid": "N[C@@H](CC(=O)O)C(=O)O", "L-arginine": "N=C(N)NCCC[C@H](N)C(=O)O",
    "L-methionine": "CSCC[C@H](N)C(=O)O", "L-tyrosine": "N[C@@H](Cc1ccc(O)cc1)C(=O)O", "L-cysteine": "N[C@@H](CS)C(=O)O",
    "4-aminobenzoic acid": "Nc1ccc(cc1)C(=O)O", "acetic acid": "CC(=O)O", "benzoic acid": "OC(=O)c1ccccc1",
    "salicylic acid": "O=C(O)c1ccccc1O", "phenol": "Oc1ccccc1", "p-nitrophenol": "O=[N+]([O-])c1ccc(O)cc1",
    "imidazole": "c1c[nH]cn1", "aniline": "Nc1ccccc1", "nicotinamide": "NC(=O)c1cccnc1", "adenine": "Nc1ncnc2[nH]cnc12",
    "adenosine": "Nc1ncnc2c1ncn2[C@@H]1O[C@H](CO)[C@@H](O)[C@H]1O", "citric acid": "OC(=O)CC(O)(CC(=O)O)C(=O)O",
    "aspirin": "CC(=O)Oc1ccccc1C(=O)O",
}
# Coverage panel (added 2026-10-05). The groups the engine-A duplicate-site bug hit (secondary/tertiary amines, primary
# amides, sulfonamides, imides) were absent from IUPAC_SET, so fixing that bug moved no metric. Scored like IUPAC_SET
# but kept OUT of the headline summary (historical numbers stay comparable) and reported as summary[engine]["coverage"].
# Left out: acetamide (its only measured step lies below pH 0, outside the read-off grid, so nearest-crossing pairing
# would score the pairing rule, not the engine) and N-methylmorpholine (one usable row).
COVERAGE = "IUPAC-coverage"
IUPAC_COVERAGE_SET = {
    "ethylamine": "CCN", "dimethylamine": "CNC", "diethylamine": "CCNCC", "trimethylamine": "CN(C)C",
    "triethylamine": "CCN(CC)CC", "diisopropylamine": "CC(C)NC(C)C", "pyrrolidine": "C1CCNC1", "piperidine": "C1CCNCC1",
    "N-methylpiperidine": "CN1CCCCC1", "morpholine": "C1COCCN1", "piperazine": "C1CNCCN1", "sarcosine": "CNCC(=O)O",
    "N,N-dimethylglycine": "CN(C)CC(=O)O", "L-proline": "OC(=O)[C@@H]1CCCN1",
    "glycinamide": "NCC(N)=O", "benzenesulfonamide": "NS(=O)(=O)c1ccccc1", "sulfanilamide": "Nc1ccc(cc1)S(N)(=O)=O",
    "saccharin": "O=C1NS(=O)(=O)c2ccccc12", "succinimide": "O=C1CCC(=O)N1",
}
PKA_TYPE = re.compile(r"^pKa(H?)(\d)$")


# ------------------------------------------------------------------------------------------------
# reference (measured) model
# ------------------------------------------------------------------------------------------------
def macro_charge(pkas: list[float], q_max: int, ph: float) -> float:
    """Sequential macro dissociation model. pkas ascending = steps from the +q_max species downward."""
    pk = sorted(pkas)
    logs = [0.0]
    acc = 0.0
    for k, p in enumerate(pk, start=1):
        acc += p
        logs.append(k * ph - acc)
    mx = max(logs)
    w = [10.0 ** (v - mx) for v in logs]
    s = sum(w)
    return sum(wi * (q_max - k) for k, wi in enumerate(w)) / s


def macro_curve(pkas, q_max, grid=GRID):
    return [{"ph": p, "z": round(macro_charge(pkas, q_max, p), 6)} for p in grid]


def crossings(curve: list[dict]) -> list[float]:
    """pH values where a monotone Z(pH) crosses each half-integer level between its ends → macro pKa read-off."""
    z = [r["z"] for r in curve]; ph = [r["ph"] for r in curve]
    hi, lo = z[0], z[-1]
    levels = [m + 0.5 for m in range(math.floor(lo), math.ceil(hi))]
    out = []
    for lv in levels:
        for i in range(len(z) - 1):
            if (z[i] - lv) * (z[i + 1] - lv) <= 0 and z[i] != z[i + 1]:
                t = (z[i] - lv) / (z[i] - z[i + 1])
                out.append(round(ph[i] + t * (ph[i + 1] - ph[i]), 3)); break
    return sorted(out)


def pI_of(curve):
    z = [r["z"] for r in curve]; ph = [r["ph"] for r in curve]
    for i in range(len(z) - 1):
        if z[i] > 0 >= z[i + 1] or z[i] >= 0 > z[i + 1]:
            if z[i] == z[i + 1]:
                return ph[i]
            t = z[i] / (z[i] - z[i + 1]); return round(ph[i] + t * (ph[i + 1] - ph[i]), 3)
    return None


# ------------------------------------------------------------------------------------------------
# reference set A — IUPAC
# ------------------------------------------------------------------------------------------------
def _inchis_for(smiles: str) -> list[str]:
    from rdkit import Chem
    from rdkit.Chem import inchi
    from rdkit import RDLogger
    RDLogger.DisableLog("rdApp.*")
    m = Chem.MolFromSmiles(smiles)
    out = [inchi.MolToInchi(m)]
    m2 = Chem.MolFromSmiles(smiles); Chem.RemoveStereochemistry(m2)
    i2 = inchi.MolToInchi(m2)
    if i2 not in out:
        out.append(i2)
    return out


def _t_ok(t: str) -> bool:
    try:
        return 20.0 <= float(t) <= 30.0
    except ValueError:
        return False


def load_iupac(path: str, names: dict[str, str]) -> dict[str, dict]:
    if not os.path.isfile(path):
        return {}
    want = {}
    for name, smi in names.items():
        for rank, ik in enumerate(_inchis_for(smi)):
            want.setdefault(ik, []).append((name, rank))
    rows: dict[str, list[dict]] = {}
    with open(path, newline="", encoding="utf-8") as fh:
        for r in csv.DictReader(fh):
            for name, rank in want.get(r["InChI"], []):
                rows.setdefault(name, []).append(dict(r, _rank=rank))
    out = {}
    for name, rs in rows.items():
        best_rank = min(r["_rank"] for r in rs)
        usable = [r for r in rs if r["_rank"] == best_rank and not r["cosolvent"].strip()
                  and r["assessment"].strip() in ("Reliable", "Approximate") and _t_ok(r["T"]) and PKA_TYPE.match(r["pka_type"].strip())]
        by_type: dict[str, list[float]] = {}
        for r in usable:
            try:
                v = float(r["pka_value"])
            except ValueError:
                continue
            if -2.0 <= v <= 16.0:
                by_type.setdefault(r["pka_type"].strip(), []).append(v)
        if not by_type:
            continue
        steps = []
        for t, vals in by_type.items():
            m = PKA_TYPE.match(t); cation = bool(m.group(1)); n = int(m.group(2))
            order = -n if cation else n          # …, pKaH2, pKaH1, pKa1, pKa2, … (ascending charge-order index)
            steps.append({"type": t, "order": order, "median": round(statistics.median(vals), 3), "n": len(vals),
                          "min": min(vals), "max": max(vals)})
        steps.sort(key=lambda s: s["median"])   # ascending pKa = the charge ladder from the most-protonated species down
        q_max = sum(1 for s in steps if s["order"] < 0)   # count of cationic (pKaH*) steps = charge of the fully protonated form
        pkas = [s["median"] for s in steps]
        monotone = all(b > a for a, b in zip(pkas, pkas[1:]))   # strictly ascending medians = a proper sequential ladder
        out[name] = {"source": "IUPAC Dissociation-Constants v2.3 (high-confidence), medians of 20–30 °C aqueous rows "
                               "assessed Reliable/Approximate", "steps": steps, "q_max": q_max, "pkas": pkas,
                     "n_rows_usable": len(usable), "stereo_specific_rows": best_rank == 0,
                     "ok": bool(monotone and steps),
                     "note": None if monotone else "non-monotone median set — skipped"}
    return out


# ------------------------------------------------------------------------------------------------
# reference set B — SAMPL6
# ------------------------------------------------------------------------------------------------
def load_sampl6(d: str) -> dict[str, dict]:
    vals = os.path.join(d, "sampl6_pKa_experimental_values.csv")
    smi = os.path.join(d, "sampl6_molecule_ID_and_SMILES.norm.csv")
    if not (os.path.isfile(vals) and os.path.isfile(smi)):
        return {}
    smiles = {}
    with open(smi, newline="", encoding="utf-8") as fh:
        for r in csv.reader(fh):
            if len(r) >= 2 and r[0].startswith("SM"):
                smiles[r[0]] = r[1]
    out = {}
    with open(vals, newline="", encoding="utf-8") as fh:
        for r in csv.DictReader(fh):
            mid = r["Molecule ID"]
            pk = []
            for i in (1, 2, 3):
                v = (r.get(f"pKa{i} mean") or "").strip()
                if v:
                    pk.append({"pka": float(v), "sem": float((r.get(f"pKa{i} SEM") or "0") or 0)})
            if mid in smiles and pk:
                out[mid] = {"smiles": smiles[mid], "pkas": pk, "assay": r.get("Assay Type", ""),
                            "source": "SAMPL6 pKa challenge experimental data (Sirius T3 UV-metric titration)"}
    return out


# ------------------------------------------------------------------------------------------------
# comparison
# ------------------------------------------------------------------------------------------------
def load_literature_pka(path: str | None) -> dict[str, dict]:
    """reference_literature.json → {name: {smiles, pkas:[{pka,sem,assignment}], source}} for pKa read-off comparison.
    Use for molecules whose ABSOLUTE net charge depends on a low-pH phosphate convention (nucleotides): we compare the
    engine's curve inflections (read-off pKa) to the literature pKa, not the absolute Z (Sigel's caveat: conventions differ)."""
    if not path or not os.path.isfile(path):
        return {}
    out = {}
    for e in json.load(open(path, encoding="utf-8")).get("molecules", []):
        if e.get("pka_ref") and e.get("smiles"):
            out[e["name"]] = {"smiles": e["smiles"], "source": e.get("source", "literature"), "conditions": e.get("conditions", ""),
                              "pkas": [{"pka": float(r["pka"]), "sem": 0.0, "assignment": r.get("assignment", ""),
                                        "src": r.get("source", "")} for r in e["pka_ref"]]}
    return out


def compare_curves(ref: list[dict], pred: list[dict]) -> dict:
    dz = [abs(a["z"] - b["z"]) for a, b in zip(ref, pred)]
    at = {str(p): round(next(b["z"] for b in pred if abs(b["ph"] - p) < 1e-9) - next(a["z"] for a in ref if abs(a["ph"] - p) < 1e-9), 3)
          for p in (7.0, 7.4)}
    pr, pp = pI_of(ref), pI_of(pred)
    return {"max_abs_dz": round(max(dz), 3), "ph_of_max": ref[dz.index(max(dz))]["ph"], "mean_abs_dz": round(sum(dz) / len(dz), 3),
            "dz_at": at, "pI_ref": pr, "pI_pred": pp, "dpI": (round(pp - pr, 3) if (pr is not None and pp is not None) else None)}


def compare_pkas(ref_pkas: list[float], pred_pkas: list[float]) -> dict:
    rows = []
    for p in ref_pkas:
        if pred_pkas:
            q = min(pred_pkas, key=lambda x: abs(x - p)); rows.append({"ref": p, "pred": q, "delta": round(q - p, 3)})
        else:
            rows.append({"ref": p, "pred": None, "delta": None})
    d = [r["delta"] for r in rows if r["delta"] is not None]
    return {"pairs": rows, "n_ref": len(ref_pkas), "n_pred": len(pred_pkas),
            "rmse": round(math.sqrt(sum(x * x for x in d) / len(d)), 3) if d else None,
            "mae": round(sum(abs(x) for x in d) / len(d), 3) if d else None,
            "n_missed_gt2": sum(1 for x in d if abs(x) > 2.0) + sum(1 for r in rows if r["delta"] is None)}


def run(engine: str, iupac_csv: str, sampl6_dir: str, extra_json: str | None) -> dict:
    report = {"tool": "validate_reference", "engine_request": engine, "sets": {}}
    # ---- A + C: curve-level validation --------------------------------------------------------
    refs = {}
    iu = load_iupac(iupac_csv, IUPAC_SET)
    for name, rec in iu.items():
        if rec["ok"]:
            refs[name] = dict(rec, smiles=IUPAC_SET[name], set="IUPAC")
    iu_cov = load_iupac(iupac_csv, IUPAC_COVERAGE_SET)
    for name, rec in iu_cov.items():
        if rec["ok"]:
            refs[name] = dict(rec, smiles=IUPAC_COVERAGE_SET[name], set=COVERAGE)
    if extra_json and os.path.isfile(extra_json):
        for e in json.load(open(extra_json, encoding="utf-8")).get("molecules", []):
            if e.get("pkas") and e.get("smiles"):
                refs[e["name"]] = {"smiles": e["smiles"], "pkas": sorted(e["pkas"]), "q_max": int(e["q_max"]),
                                   "source": e.get("source", "literature"), "conditions": e.get("conditions"), "ok": True, "set": "literature"}
    curve_rows = {}
    for name, rec in refs.items():
        ref_curve = macro_curve(rec["pkas"], rec["q_max"])
        res = cvp.compute(rec["smiles"], ph="0:14:0.1", at=[7.0, 7.4], engine=engine)
        entry = {"set": rec["set"], "smiles": rec["smiles"], "inchikey": (res.get("identity") or {}).get("inchikey"),
                 "reference": {"pkas": rec["pkas"], "q_max": rec["q_max"], "source": rec["source"],
                               "steps": rec.get("steps"), "conditions": rec.get("conditions"), "pI": pI_of(ref_curve)},
                 "engines": {}}
        for en, blk in (res.get("engines") or {}).items():
            if not blk.get("ok"):
                entry["engines"][en] = {"ok": False, "error": blk.get("error")}; continue
            pred_curve = [{"ph": r["ph"], "z": r["z"]} for r in blk["curve"]]
            entry["engines"][en] = {"ok": True, "version": blk.get("version"),
                                    "curve_metrics": compare_curves(ref_curve, pred_curve),
                                    "pka_readoff": crossings(pred_curve),
                                    "pka_metrics": compare_pkas(rec["pkas"], crossings(pred_curve)),
                                    "q0": blk.get("q0"), "limits": blk.get("limits"),
                                    "sites": [(s["moiety"], s["kind"], s["pka"]) for s in blk.get("sites", [])] if en == "dimorphite" else None}
        curve_rows[name] = entry
    report["sets"]["curves"] = curve_rows
    # ---- B: SAMPL6 pKa-level validation --------------------------------------------------------
    s6 = load_sampl6(sampl6_dir)
    s6_rows = {}
    for mid, rec in s6.items():
        res = cvp.compute(rec["smiles"], ph="0:14:0.1", engine=engine)
        entry = {"smiles": rec["smiles"], "inchikey": (res.get("identity") or {}).get("inchikey"),
                 "reference": {"pkas": [p["pka"] for p in rec["pkas"]], "sem": [p["sem"] for p in rec["pkas"]], "source": rec["source"]},
                 "engines": {}}
        for en, blk in (res.get("engines") or {}).items():
            if not blk.get("ok"):
                entry["engines"][en] = {"ok": False, "error": blk.get("error")}; continue
            pred_curve = [{"ph": r["ph"], "z": r["z"]} for r in blk["curve"]]
            ro = crossings(pred_curve)
            entry["engines"][en] = {"ok": True, "pka_readoff": ro, "pka_metrics": compare_pkas([p["pka"] for p in rec["pkas"]], ro)}
        s6_rows[mid] = entry
    report["sets"]["sampl6"] = s6_rows
    # ---- literature pKa read-off (nucleotides etc.): compare inflections, not absolute Z ------
    lit = load_literature_pka(extra_json)
    lit_rows = {}
    for name, rec in lit.items():
        res = cvp.compute(rec["smiles"], ph="0:14:0.1", at=[7.0, 7.4], engine=engine)
        entry = {"smiles": rec["smiles"], "inchikey": (res.get("identity") or {}).get("inchikey"),
                 "reference": {"pkas": [p["pka"] for p in rec["pkas"]], "assignments": [p["assignment"] for p in rec["pkas"]],
                               "source": rec["source"], "conditions": rec["conditions"], "per_pka_source": [p["src"] for p in rec["pkas"]]},
                 "engines": {}}
        for en, blk in (res.get("engines") or {}).items():
            if not blk.get("ok"):
                entry["engines"][en] = {"ok": False, "error": blk.get("error")}; continue
            pred_curve = [{"ph": r["ph"], "z": r["z"]} for r in blk["curve"]]
            ro = crossings(pred_curve)
            entry["engines"][en] = {"ok": True, "pka_readoff": ro, "pka_metrics": compare_pkas([p["pka"] for p in rec["pkas"]], ro),
                                    "q0": blk.get("q0"), "z_at": {str(p["ph"]): p["z"] for p in blk.get("z_at", [])},
                                    "pI": blk.get("pI"), "limits": blk.get("limits"),
                                    "sites": [(x["moiety"], x["kind"], x["pka"]) for x in blk.get("sites", [])] if en == "dimorphite" else None}
        lit_rows[name] = entry
    report["sets"]["literature"] = lit_rows
    # ---- summaries --------------------------------------------------------------------------
    summ = {}
    for en in cvp.ENGINES:
        head = [e for e in curve_rows.values() if e["set"] != COVERAGE and e["engines"].get(en, {}).get("ok")]
        cov = [e for e in curve_rows.values() if e["set"] == COVERAGE and e["engines"].get(en, {}).get("ok")]
        cm = [e["engines"][en]["curve_metrics"] for e in head]
        pk = [d["delta"] for e in head for d in e["engines"][en]["pka_metrics"]["pairs"] if d["delta"] is not None]
        ccm = [e["engines"][en]["curve_metrics"] for e in cov]
        cpk = [d["delta"] for e in cov for d in e["engines"][en]["pka_metrics"]["pairs"] if d["delta"] is not None]
        s6d = [d["delta"] for e in s6_rows.values() if e["engines"].get(en, {}).get("ok")
               for d in e["engines"][en]["pka_metrics"]["pairs"] if d["delta"] is not None]
        litd = [d["delta"] for e in lit_rows.values() if e["engines"].get(en, {}).get("ok")
                for d in e["engines"][en]["pka_metrics"]["pairs"] if d["delta"] is not None]
        if not cm and not s6d and not litd and not ccm:
            continue
        summ[en] = {
            "n_curve_molecules": len(cm),
            "median_max_abs_dz": round(statistics.median([c["max_abs_dz"] for c in cm]), 3) if cm else None,
            "worst_max_abs_dz": round(max(c["max_abs_dz"] for c in cm), 3) if cm else None,
            "median_abs_dz_at_7.4": round(statistics.median([abs(c["dz_at"]["7.4"]) for c in cm]), 3) if cm else None,
            "n_with_pI_both": sum(1 for c in cm if c["dpI"] is not None),
            "median_abs_dpI": round(statistics.median([abs(c["dpI"]) for c in cm if c["dpI"] is not None]), 3) if any(c["dpI"] is not None for c in cm) else None,
            "iupac_lit_pka_rmse": round(math.sqrt(sum(x * x for x in pk) / len(pk)), 3) if pk else None,
            "iupac_lit_pka_n": len(pk),
            "sampl6_pka_rmse": round(math.sqrt(sum(x * x for x in s6d) / len(s6d)), 3) if s6d else None,
            "sampl6_pka_mae": round(sum(abs(x) for x in s6d) / len(s6d), 3) if s6d else None,
            "sampl6_pka_n": len(s6d), "sampl6_n_molecules": sum(1 for e in s6_rows.values() if e["engines"].get(en, {}).get("ok")),
            "sampl6_n_missed_gt2": sum(1 for x in s6d if abs(x) > 2.0),
            "literature_pka_rmse": round(math.sqrt(sum(x * x for x in litd) / len(litd)), 3) if litd else None,
            "literature_pka_mae": round(sum(abs(x) for x in litd) / len(litd), 3) if litd else None,
            "literature_pka_n": len(litd),
            "coverage": {"n_molecules": len(ccm),
                         "median_abs_dz_at_7.4": round(statistics.median([abs(c["dz_at"]["7.4"]) for c in ccm]), 3) if ccm else None,
                         "worst_abs_dz_at_7.4": round(max(abs(c["dz_at"]["7.4"]) for c in ccm), 3) if ccm else None,
                         "pka_rmse": round(math.sqrt(sum(x * x for x in cpk) / len(cpk)), 3) if cpk else None,
                         "pka_mae": round(sum(abs(x) for x in cpk) / len(cpk), 3) if cpk else None,
                         "pka_n": len(cpk), "n_missed_gt2": sum(1 for x in cpk if abs(x) > 2.0)},
        }
    report["summary"] = summ
    report["data"] = {"iupac_csv": iupac_csv if os.path.isfile(iupac_csv) else None, "sampl6_dir": sampl6_dir if s6 else None,
                      "extra_json": extra_json if (extra_json and os.path.isfile(extra_json)) else None,
                      "n_iupac_loaded": len(iu), "n_iupac_ok": sum(1 for r in iu.values() if r["ok"]), "n_sampl6": len(s6),
                      "n_coverage_loaded": len(iu_cov), "n_coverage_ok": sum(1 for r in iu_cov.values() if r["ok"])}
    return report


def markdown(report: dict) -> str:
    L = ["# charge_vs_ph — cross-validation against measured pKa", ""]
    L.append(f"Data: IUPAC rows loaded {report['data']['n_iupac_loaded']} (usable {report['data']['n_iupac_ok']}), SAMPL6 molecules {report['data']['n_sampl6']}, "
             f"extra literature file: {'yes' if report['data']['extra_json'] else 'no'}")
    L.append("")
    L.append("## Summary per engine")
    L.append("| engine | n curves | median max abs dZ | worst max abs dZ | median abs dZ @7.4 | median abs dpI (n) | IUPAC/lit pKa RMSE (n) | SAMPL6 pKa RMSE / MAE (n, missed>2) |")
    L.append("|---|---|---|---|---|---|---|---|")
    for en, s in report["summary"].items():
        L.append(f"| {en} | {s['n_curve_molecules']} | {s['median_max_abs_dz']} | {s['worst_max_abs_dz']} | {s['median_abs_dz_at_7.4']} | "
                 f"{s['median_abs_dpI']} ({s['n_with_pI_both']}) | {s['iupac_lit_pka_rmse']} ({s['iupac_lit_pka_n']}) | "
                 f"{s['sampl6_pka_rmse']} / {s['sampl6_pka_mae']} ({s['sampl6_pka_n']}, {s['sampl6_n_missed_gt2']}) |")
    L.append("")
    L.append(f"Coverage panel ({COVERAGE}: secondary/tertiary amines, amides, sulfonamides, imides; not in the headline above):")
    L.append("| engine | n | median abs dZ @7.4 | worst abs dZ @7.4 | pKa RMSE / MAE (n, missed>2) |")
    L.append("|---|---|---|---|---|")
    for en, s in report["summary"].items():
        c = s["coverage"]
        L.append(f"| {en} | {c['n_molecules']} | {c['median_abs_dz_at_7.4']} | {c['worst_abs_dz_at_7.4']} | {c['pka_rmse']} / {c['pka_mae']} ({c['pka_n']}, {c['n_missed_gt2']}) |")
    L.append("")
    L.append("## Curve-level (measured macro pKa → reference Z(pH))")
    L.append("| molecule | set | ref pKa (q_max) | engine | max abs dZ @pH | dZ @7.4 | pI ref → pred | pKa read-off | pKa RMSE |")
    L.append("|---|---|---|---|---|---|---|---|---|")
    for name, e in report["sets"]["curves"].items():
        for en, b in e["engines"].items():
            if not b.get("ok"):
                L.append(f"| {name} | {e['set']} | {e['reference']['pkas']} ({e['reference']['q_max']}) | {en} | not run: {b.get('error')} | | | | |"); continue
            c = b["curve_metrics"]
            L.append(f"| {name} | {e['set']} | {e['reference']['pkas']} ({e['reference']['q_max']}) | {en} | {c['max_abs_dz']} @{c['ph_of_max']} | "
                     f"{c['dz_at']['7.4']:+} | {c['pI_ref']} → {c['pI_pred']} | {b['pka_readoff']} | {b['pka_metrics']['rmse']} |")
    L.append("")
    L.append("## Literature nucleotides (pKa read-off; absolute Z is convention-dependent, so inflections are compared)")
    L.append("| molecule | InChIKey | exp pKa (assignment) | engine | read-off pKa | Δ | Z@7.4 | q0 |")
    L.append("|---|---|---|---|---|---|---|---|")
    for nm, e in report["sets"].get("literature", {}).items():
        for en, b in e["engines"].items():
            if not b.get("ok"):
                L.append(f"| {nm} | {e['inchikey']} | {e['reference']['pkas']} | {en} | not run: {b.get('error')} | | | |"); continue
            L.append(f"| {nm} | {e['inchikey']} | {list(zip(e['reference']['pkas'], e['reference']['assignments']))} | {en} | "
                     f"{b['pka_readoff']} | {[p['delta'] for p in b['pka_metrics']['pairs']]} | {b['z_at'].get('7.4')} | {b['q0']} |")
    L.append("")
    L.append("## SAMPL6 (pKa-level)")
    L.append("| ID | exp pKa | engine | read-off pKa | Δ per exp pKa | RMSE |")
    L.append("|---|---|---|---|---|---|")
    for mid, e in report["sets"]["sampl6"].items():
        for en, b in e["engines"].items():
            if not b.get("ok"):
                continue
            L.append(f"| {mid} | {e['reference']['pkas']} | {en} | {b['pka_readoff']} | {[p['delta'] for p in b['pka_metrics']['pairs']]} | {b['pka_metrics']['rmse']} |")
    return "\n".join(L) + "\n"


def selftest() -> int:
    ok = 0; bad = 0
    def gate(d, c, extra=""):
        nonlocal ok, bad
        if c: ok += 1; print(f"  PASS  {d}")
        else: bad += 1; print(f"  FAIL  {d}  {extra}")
    print("== validate_reference selftest ==")
    # 1 macro model reduces to HH when steps are far apart (glycine-like: base 9.8, acid 2.3)
    ref = macro_charge([2.3, 9.8], 1, 7.0); hh = cvp.hh_charge([{"kind": "acid", "pka": 2.3}, {"kind": "base", "pka": 9.8}], 0, 7.0)
    gate("1 macro model = independent-site HH for well-separated steps", abs(ref - hh) < 1e-6, f"{ref} vs {hh}")
    # 2 macro model limits
    gate("2 macro limits: Z(-60)=q_max, Z(+60)=q_max-n", abs(macro_charge([2, 9], 1, -60) - 1) < 1e-9 and abs(macro_charge([2, 9], 1, 60) + 1) < 1e-9)
    # 3 crossings read-off recovers the pKa of a synthetic curve
    cur = macro_curve([3.0, 8.0], 1); ro = crossings(cur)
    gate("3 half-integer crossings read off macro pKa (3.0, 8.0) within 0.05", len(ro) == 2 and abs(ro[0] - 3.0) < 0.05 and abs(ro[1] - 8.0) < 0.05, str(ro))
    # 4 pI read-off
    gate("4 pI read-off of a synthetic glycine-like curve ≈ 5.5", abs((pI_of(cur) or 0) - 5.5) < 0.05, str(pI_of(cur)))
    # 5 IUPAC loader (skips if data absent)
    if os.path.isfile(IUPAC_CSV):
        iu = load_iupac(IUPAC_CSV, {"glycine": IUPAC_SET["glycine"], "L-lysine": IUPAC_SET["L-lysine"]})
        g = iu.get("glycine", {})
        gate("5 IUPAC glycine: q_max=1, two steps, medians inside the textbook window (2.2-2.5 / 9.5-9.9)",
             g.get("ok") and g.get("q_max") == 1 and len(g.get("pkas", [])) == 2
             and 2.2 <= g["pkas"][0] <= 2.5 and 9.5 <= g["pkas"][1] <= 9.9, str(g.get("pkas")))
        ly = iu.get("L-lysine", {})
        gate("6 IUPAC lysine: q_max=2, three contiguous ascending steps (~2.2 / 9.1 / 10.8)",
             ly.get("ok") and ly.get("q_max") == 2 and len(ly.get("pkas", [])) == 3
             and 1.9 <= ly["pkas"][0] <= 2.5 and 8.8 <= ly["pkas"][1] <= 9.4 and 10.4 <= ly["pkas"][2] <= 11.1, str(ly.get("pkas")))
        cov = load_iupac(IUPAC_CSV, IUPAC_COVERAGE_SET)
        miss = sorted(n for n in IUPAC_COVERAGE_SET if not cov.get(n, {}).get("ok"))
        gate(f"9 coverage panel: all {len(IUPAC_COVERAGE_SET)} entries load from IUPAC with a usable step ladder", not miss, str(miss))
    else:
        print("  SKIP  5/6/9 IUPAC csv absent:", IUPAC_CSV)
    # 7 SAMPL6 loader
    s6 = load_sampl6(SAMPL6_DIR)
    if s6:
        gate("7 SAMPL6: 24 molecules with SMILES + ≥1 experimental pKa", len(s6) == 24, str(len(s6)))
    else:
        print("  SKIP  7 SAMPL6 files absent in", SAMPL6_DIR)
    # 8 compare_pkas pairing
    m = compare_pkas([3.0, 8.0], [2.5, 8.6, 12.0])
    gate("8 nearest-pKa pairing: deltas −0.5 / +0.6, RMSE 0.552", m["pairs"][0]["delta"] == -0.5 and m["pairs"][1]["delta"] == 0.6 and abs(m["rmse"] - 0.552) < 1e-3, str(m))
    print(f"selftest: {ok}/{ok + bad} passed")
    return 0 if bad == 0 else 1


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description="cross-validate charge_vs_ph engines against measured pKa (IUPAC, SAMPL6, literature)")
    ap.add_argument("--engine", default="auto", choices=("auto", "all") + cvp.ENGINES)
    ap.add_argument("--iupac", default=IUPAC_CSV)
    ap.add_argument("--sampl6", default=SAMPL6_DIR)
    ap.add_argument("--extra", default=EXTRA_JSON)
    ap.add_argument("--out", help="STEM → STEM.json + STEM.md")
    ap.add_argument("--selftest", action="store_true")
    a = ap.parse_args(argv)
    if a.selftest:
        return selftest()
    rep = run(a.engine, a.iupac, a.sampl6, a.extra)
    md = markdown(rep)
    if a.out:
        os.makedirs(os.path.dirname(os.path.abspath(a.out)) or ".", exist_ok=True)
        json.dump(rep, open(a.out + ".json", "w"), ensure_ascii=False, indent=1)
        open(a.out + ".md", "w").write(md)
        print(f"written: {a.out}.json {a.out}.md")
    print(md)
    return 0


if __name__ == "__main__":
    sys.exit(main())
